/**
 * deploy-phase22.js — Deploy PHGRegistry + TournamentGate (Phase 22)
 *
 * Usage:
 *   npx hardhat run scripts/deploy-phase22.js --network iotex_testnet
 *   npx hardhat run scripts/deploy-phase22.js --network iotex_mainnet
 *
 * Env vars required:
 *   BRIDGE_ADDRESS    — Ethereum address of the VAPI bridge wallet (onlyBridge caller)
 *   MIN_PHG_SCORE     — Minimum PHG score for TournamentGate (default: 100)
 *
 * Outputs:
 *   Deployment addresses logged to stdout
 *   Appended to bridge/.env.phase22 (created if absent)
 */

const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying Phase 22 contracts...");
  console.log("  Deployer:", deployer.address);

  // --- Config ---
  const bridgeAddress = process.env.BRIDGE_ADDRESS || deployer.address;
  const minPHGScore   = BigInt(process.env.MIN_PHG_SCORE || "100");

  if (!process.env.BRIDGE_ADDRESS) {
    console.warn("  BRIDGE_ADDRESS not set — using deployer address as bridge.");
  }

  // --- Deploy PHGRegistry ---
  console.log("\nDeploying PHGRegistry...");
  const PHGRegistry = await ethers.getContractFactory("PHGRegistry");
  const registry = await PHGRegistry.deploy(bridgeAddress);
  await registry.waitForDeployment();
  const registryAddress = await registry.getAddress();
  console.log("  PHGRegistry deployed:", registryAddress);
  console.log("  bridge:", bridgeAddress);

  // --- Deploy TournamentGate ---
  console.log("\nDeploying TournamentGate...");
  const TournamentGate = await ethers.getContractFactory("TournamentGate");
  const gate = await TournamentGate.deploy(registryAddress, minPHGScore);
  await gate.waitForDeployment();
  const gateAddress = await gate.getAddress();
  console.log("  TournamentGate deployed:", gateAddress);
  console.log("  phgRegistry:", registryAddress);
  console.log("  minPHGScore:", minPHGScore.toString());

  // --- Smoke test ---
  const bridgeFromContract = await registry.bridge();
  if (bridgeFromContract.toLowerCase() !== bridgeAddress.toLowerCase()) {
    throw new Error("Bridge address mismatch in deployed contract");
  }
  const registryFromGate = await gate.phgRegistry();
  if (registryFromGate.toLowerCase() !== registryAddress.toLowerCase()) {
    throw new Error("Registry address mismatch in TournamentGate");
  }
  console.log("\n✓ Smoke tests passed");

  // --- Write env file ---
  const envPath = path.resolve(__dirname, "../../bridge/.env.phase22");
  const envContent = [
    `# Phase 22 — PHG Registry (generated by deploy-phase22.js)`,
    `# Network: ${hre.network.name}`,
    `# Deployed at: ${new Date().toISOString()}`,
    ``,
    `PHG_REGISTRY_ADDRESS=${registryAddress}`,
    `TOURNAMENT_GATE_ADDRESS=${gateAddress}`,
    `PHG_CHECKPOINT_INTERVAL=10`,
    ``,
  ].join("\n");

  fs.appendFileSync(envPath, envContent);
  console.log("\nAddresses appended to:", envPath);

  // --- Summary ---
  console.log("\n=== Phase 22 Deployment Summary ===");
  console.log(`PHG_REGISTRY_ADDRESS=${registryAddress}`);
  console.log(`TOURNAMENT_GATE_ADDRESS=${gateAddress}`);
  console.log(`PHG_CHECKPOINT_INTERVAL=10`);
  console.log("\nNext steps:");
  console.log("  1. Copy PHG_REGISTRY_ADDRESS to bridge/.env");
  console.log("  2. Restart the bridge — checkpoints will begin after first 10 NOMINAL records");
  console.log("  3. Monitor: GET /dash/api/v1/player/{device_id}/checkpoint-chain");
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
