// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/**
 * @title ITeamProofVerifier
 * @author VAPI Project
 * @notice Interface for the auto-generated snarkjs Groth16 verifier contract.
 *
 * @dev The concrete implementation is generated by:
 *        cd contracts/circuits && bash setup.sh
 *      which produces contracts/contracts/TeamProofVerifier.sol via:
 *        npx snarkjs zkey export solidityverifier TeamProof_final.zkey TeamProofVerifier.sol
 *
 *      Circuit public inputs (must match contracts/circuits/TeamProof.circom order):
 *        [0] poseidonMerkleRoot  — Poseidon tree root of 8-leaf commitment tree
 *        [1] nullifierHash       — Poseidon(poseidonMerkleRoot, identitySecrets[0], epoch)
 *        [2] memberCount         — Active member count in [2, 6]
 *        [3] epoch               — block.number / EPOCH_BLOCKS (anti-replay domain tag)
 *
 *      Proof wire format (256 bytes, ABI-packed):
 *        bytes[0:64]    a   — G1 point (pi_a.x, pi_a.y)
 *        bytes[64:192]  b   — G2 point (pi_b[0][0], pi_b[0][1], pi_b[1][0], pi_b[1][1])
 *        bytes[192:256] c   — G1 point (pi_c.x, pi_c.y)
 *
 *      Decode via: abi.decode(proof, (uint256[2], uint256[2][2], uint256[2]))
 */
interface ITeamProofVerifier {
    /**
     * @notice Verify a Groth16 BN254 proof against the TeamProof circuit.
     *
     * @param a      G1 proof component (pi_a): [x, y]
     * @param b      G2 proof component (pi_b): [[x0, x1], [y0, y1]]
     * @param c      G1 proof component (pi_c): [x, y]
     * @param input  Public inputs in circuit declaration order:
     *                 input[0] = poseidonMerkleRoot
     *                 input[1] = nullifierHash (as uint256)
     *                 input[2] = memberCount
     *                 input[3] = epoch
     * @return       True if the proof is valid.
     */
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[4] memory input
    ) external view returns (bool);
}
