// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

import "./TeamProofAggregator.sol";
import "./ITeamProofVerifier.sol";

/**
 * @title TeamProofAggregatorZK
 * @author VAPI Project
 * @notice Extends TeamProofAggregator with a ZK proof gate for privacy-preserving
 *         team attestation.
 *
 * @dev Architecture (Phase 14C):
 *      - submitTeamProofZK() (5-param) — Phase 13 backward-compat; mock proof path.
 *      - submitTeamProofZK() (7-param) — Phase 14C real path; requires poseidonMerkleRoot
 *        and epoch, which the Python ZKProver (bridge/zk_prover.py) provides.
 *      - _verifyZKProof() is virtual — upgraded to real Groth16 when teamProofVerifier
 *        is set to the address of the auto-generated TeamProofVerifier.sol contract.
 *      - usedNullifiers prevents replay: each nullifierHash may only be used once.
 *
 *      Two-mode operation:
 *        Mock path (teamProofVerifier == address(0) OR poseidonMerkleRoot == 0):
 *          _verifyZKProof returns true iff proof.length == MOCK_PROOF_SIZE (256 bytes).
 *          Compatible with all Phase 13 tests and the Phase 14C mock fallback in
 *          bridge/zk_prover.py.
 *
 *        Real path (teamProofVerifier set, poseidonMerkleRoot != 0):
 *          Decodes the 256-byte ABI-packed proof into (G1, G2, G1) components.
 *          Calls ITeamProofVerifier.verifyProof() with the decoded components and
 *          four public inputs: [poseidonMerkleRoot, nullifierHash, memberCount, epoch].
 *
 * ZK Circuit: contracts/circuits/TeamProof.circom
 * ─────────────────────────────────────────────────────────────────────────────
 *   Public inputs (order matches circuit declaration):
 *     poseidonMerkleRoot : uint256  — Poseidon tree root of 8-leaf commitment tree
 *     nullifierHash      : uint256  — Poseidon(poseidonMerkleRoot, identitySecrets[0], epoch)
 *     memberCount        : uint256  — Active members in [2, 6]
 *     epoch              : uint256  — block.number / EPOCH_BLOCKS (anti-replay)
 *
 *   Private inputs:
 *     inferenceResults[6] — 8-bit VAPI inference codes (secret; must not be in [40, 42])
 *     identitySecrets[6]  — Poseidon(deviceId) per member
 *     activeFlags[6]      — 1 = active slot; sum == memberCount
 *
 *   Proof wire format (256 bytes; abi.decode compatible):
 *     [0:64]    a   — G1 point (pi_a.x, pi_a.y)
 *     [64:192]  b   — G2 point (pi_b[0][0..1], pi_b[1][0..1])
 *     [192:256] c   — G1 point (pi_c.x, pi_c.y)
 *
 * Setup:
 *   1. cd contracts/circuits && npm install && bash setup.sh
 *   2. Deploy TeamProofVerifier.sol (auto-generated at contracts/contracts/TeamProofVerifier.sol)
 *   3. Call setTeamProofVerifier(<TeamProofVerifier address>)
 *   4. Bridge: set VAPI_ZK_WASM_PATH / VAPI_ZK_ZKEY_PATH / VAPI_ZK_VKEY_PATH
 *   5. Submit proofs via 7-param submitTeamProofZK()
 */
contract TeamProofAggregatorZK is TeamProofAggregator {

    bytes32 public constant ZK_VERSION = keccak256("TeamProofZK_Groth16_Phase14");

    /// @notice Expected proof byte length (Phase 13 mock + Phase 14C real Groth16).
    uint256 public constant MOCK_PROOF_SIZE = 256;

    // ─── Errors ─────────────────────────────────────────────────────────

    error InvalidZKProof();
    error NullifierAlreadyUsed(bytes32 nullifier);

    // ─── State ──────────────────────────────────────────────────────────

    /// @notice Tracks used nullifiers to prevent ZK proof replay.
    mapping(bytes32 => bool) public usedNullifiers;

    /**
     * @notice Address of the Groth16 verifier contract (ITeamProofVerifier).
     * @dev    address(0) = mock path (Phase 13 compat / pre-setup).
     *         Set via setTeamProofVerifier() after deploying the auto-generated verifier.
     */
    address public teamProofVerifier;

    // ─── Events ─────────────────────────────────────────────────────────

    event ZKTeamProofSubmitted(
        bytes32 indexed teamId,
        bytes32 indexed merkleRoot,
        bytes32 nullifierHash,
        uint256 memberCount
    );

    /// @notice Emitted when the Groth16 verifier contract address is updated.
    event TeamProofVerifierSet(address indexed verifier);

    // ─── Constructor ────────────────────────────────────────────────────

    constructor(address _poACVerifier) TeamProofAggregator(_poACVerifier) {
        // teamProofVerifier defaults to address(0) — mock path active until set
    }

    // ─── Admin ──────────────────────────────────────────────────────────

    /**
     * @notice Set the address of the Groth16 verifier contract.
     * @dev    Deploy contracts/contracts/TeamProofVerifier.sol (auto-generated by setup.sh)
     *         and pass its address here to activate real proof verification.
     *         Pass address(0) to revert to mock path.
     * @param  _verifier  ITeamProofVerifier contract address.
     */
    function setTeamProofVerifier(address _verifier) external onlyOwner {
        teamProofVerifier = _verifier;
        emit TeamProofVerifierSet(_verifier);
    }

    // ─── ZK-Gated Submission (Phase 13 backward-compat) ─────────────────

    /**
     * @notice Submit a team proof with a ZK proof (Phase 13 / mock fallback signature).
     *
     * @dev    Backward-compatible with all Phase 13 tests and the mock proof path in
     *         bridge/zk_prover.py. Sets poseidonMerkleRoot=0 and epoch=0, which
     *         forces the mock verification path regardless of teamProofVerifier.
     *
     * @param _teamId         Team identifier.
     * @param _recordHashes   SHA-256 hashes of each member's PoAC record body.
     * @param _merkleRoot     Sorted keccak256 Merkle root of _recordHashes.
     * @param _nullifierHash  Anti-replay nullifier (each may only be used once).
     * @param _zkProof        ZK proof bytes; mock path: any 256-byte payload accepted.
     * @return proofId        Unique ID from the parent TeamProofAggregator.
     */
    function submitTeamProofZK(
        bytes32   _teamId,
        bytes32[] calldata _recordHashes,
        bytes32   _merkleRoot,
        bytes32   _nullifierHash,
        bytes calldata _zkProof
    ) external returns (uint256 proofId) {
        return _submitZK(_teamId, _recordHashes, _merkleRoot, _nullifierHash, _zkProof, 0, 0);
    }

    // ─── ZK-Gated Submission (Phase 14C real path) ───────────────────────

    /**
     * @notice Submit a team proof with a real Groth16 ZK proof (Phase 14C).
     *
     * @dev    When teamProofVerifier is set and poseidonMerkleRoot is nonzero,
     *         decodes the 256-byte proof and calls the Groth16 verifier.
     *         The Python bridge (bridge/zk_prover.py ZKProver.generate_proof()) provides
     *         poseidonMerkleRoot and epoch alongside the proof bytes.
     *
     * @param _teamId              Team identifier.
     * @param _recordHashes        SHA-256 hashes of each member's PoAC record body.
     * @param _merkleRoot          Sorted keccak256 Merkle root (for parent cheat detection).
     * @param _nullifierHash       Anti-replay nullifier: bytes32(Poseidon(root, secret0, epoch)).
     * @param _zkProof             256-byte ABI-packed Groth16 proof (A:64B + B:128B + C:64B).
     * @param _poseidonMerkleRoot  Circuit public input: Poseidon tree root (uint256 field element).
     * @param _epoch               Circuit public input: block.number / EPOCH_BLOCKS.
     * @return proofId             Unique ID from the parent TeamProofAggregator.
     */
    function submitTeamProofZK(
        bytes32   _teamId,
        bytes32[] calldata _recordHashes,
        bytes32   _merkleRoot,
        bytes32   _nullifierHash,
        bytes calldata _zkProof,
        uint256   _poseidonMerkleRoot,
        uint256   _epoch
    ) external returns (uint256 proofId) {
        return _submitZK(
            _teamId, _recordHashes, _merkleRoot, _nullifierHash,
            _zkProof, _poseidonMerkleRoot, _epoch
        );
    }

    // ─── Internal submission logic ───────────────────────────────────────

    function _submitZK(
        bytes32   _teamId,
        bytes32[] calldata _recordHashes,
        bytes32   _merkleRoot,
        bytes32   _nullifierHash,
        bytes calldata _zkProof,
        uint256   _poseidonMerkleRoot,
        uint256   _epoch
    ) internal returns (uint256 proofId) {
        if (usedNullifiers[_nullifierHash]) {
            revert NullifierAlreadyUsed(_nullifierHash);
        }
        if (!_verifyZKProof(
            _merkleRoot, _nullifierHash, _recordHashes.length,
            _zkProof, _poseidonMerkleRoot, _epoch
        )) {
            revert InvalidZKProof();
        }

        usedNullifiers[_nullifierHash] = true;

        // Delegate record verification + cheat detection + storage to parent
        proofId = submitTeamProof(_teamId, _recordHashes, _merkleRoot);

        emit ZKTeamProofSubmitted(
            _teamId,
            _merkleRoot,
            _nullifierHash,
            _recordHashes.length
        );
    }

    // ─── Virtual ZK Verifier ────────────────────────────────────────────

    /**
     * @dev Phase 14C implementation:
     *
     *      Mock path (teamProofVerifier == address(0) OR poseidonMerkleRoot == 0):
     *        Returns true iff proof.length == MOCK_PROOF_SIZE (256 bytes).
     *        This is the Phase 13 behavior — unchanged for backward compatibility.
     *
     *      Real path (teamProofVerifier set AND poseidonMerkleRoot != 0):
     *        1. Rejects proof if length != 256.
     *        2. Decodes the 256B ABI-packed proof → (uint256[2], uint256[2][2], uint256[2]).
     *        3. Builds public inputs array: [poseidonMerkleRoot, uint256(nullifierHash),
     *           memberCount, epoch] — matching the circuit's public signal declaration order.
     *        4. Calls ITeamProofVerifier.verifyProof() and returns its result.
     *
     *      Override in TeamProofAggregatorZKTestable with a configurable bool (testing).
     *
     * @param merkleRoot          keccak256 Merkle root (used only for mock path compat).
     * @param nullifierHash       Anti-replay nullifier (also a circuit public input).
     * @param memberCount         Active member count (circuit public input).
     * @param proof               256-byte ABI-packed Groth16 proof.
     * @param poseidonMerkleRoot  Poseidon commitment tree root (circuit public input).
     * @param epoch               Epoch domain tag (circuit public input).
     * @return                    True if the proof is valid.
     */
    function _verifyZKProof(
        bytes32 merkleRoot,
        bytes32 nullifierHash,
        uint256 memberCount,
        bytes calldata proof,
        uint256 poseidonMerkleRoot,
        uint256 epoch
    ) internal virtual returns (bool) {
        // Mock path: no verifier set or Poseidon root not provided
        if (teamProofVerifier == address(0) || poseidonMerkleRoot == 0) {
            // Silence unused variable warnings (used in real path)
            merkleRoot;
            return proof.length == MOCK_PROOF_SIZE;
        }

        // Real path: full Groth16 verification
        if (proof.length != MOCK_PROOF_SIZE) return false;

        // Decode 256-byte ABI-packed proof:
        //   [0:64]    a  (uint256[2])
        //   [64:192]  b  (uint256[2][2])
        //   [192:256] c  (uint256[2])
        bytes memory proofMem = proof;  // copy calldata → memory for abi.decode
        (
            uint256[2] memory a,
            uint256[2][2] memory b,
            uint256[2] memory c
        ) = abi.decode(proofMem, (uint256[2], uint256[2][2], uint256[2]));

        // Public inputs in circuit declaration order:
        //   [0] poseidonMerkleRoot
        //   [1] nullifierHash (as uint256)
        //   [2] memberCount
        //   [3] epoch
        uint256[4] memory publicInputs = [
            poseidonMerkleRoot,
            uint256(nullifierHash),
            memberCount,
            epoch
        ];

        return ITeamProofVerifier(teamProofVerifier).verifyProof(a, b, c, publicInputs);
    }
}
