#!/usr/bin/env bash
# hardware_setup.sh — DualShock Edge hardware testing prerequisites
#
# Sets up the host system for non-root USB HID access to the DualShock Edge.
# Tested on Ubuntu 22.04 / Debian 12. Adapt udev rules for other distros.
#
# Usage: bash scripts/hardware_setup.sh

set -euo pipefail

UDEV_RULE_FILE="/etc/udev/rules.d/70-dualsense-edge.rules"
VAPI_GROUP="vapi-hid"

echo "=== VAPI Hardware Setup — DualShock Edge CFI-ZCP1 ==="
echo ""

# ---------------------------------------------------------------------------
# 1. Check platform
# ---------------------------------------------------------------------------
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
  echo "NOTE: This script targets Linux (udev-based)."
  echo ""
  if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "macOS: No udev setup required. HID access is granted automatically."
    echo "Install hidapi: pip install hidapi"
  elif [[ "$OSTYPE" == "msys"* ]] || [[ "$OSTYPE" == "cygwin"* ]]; then
    echo "Windows: Use Zadig (https://zadig.akeo.ie/) to install WinUSB/LibUSB-Win32"
    echo "  driver for the DualSense Edge HID interface."
    echo "  Then: pip install hidapi"
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# 2. Install Python packages
# ---------------------------------------------------------------------------
echo "[1/4] Installing Python packages..."
if command -v pip3 &>/dev/null; then
  pip3 install --quiet hidapi pydualsense
  echo "  hidapi + pydualsense installed."
elif command -v pip &>/dev/null; then
  pip install --quiet hidapi pydualsense
  echo "  hidapi + pydualsense installed."
else
  echo "  WARNING: pip not found. Install manually: pip install hidapi pydualsense"
fi
echo ""

# ---------------------------------------------------------------------------
# 3. Install udev rules
# ---------------------------------------------------------------------------
echo "[2/4] Installing udev rules..."

if [[ $EUID -ne 0 ]]; then
  echo "  Requires root for udev rule installation. Re-running with sudo..."
  sudo bash "$0"
  exit $?
fi

cat > "$UDEV_RULE_FILE" << 'UDEV_EOF'
# VAPI hardware testing — DualShock Edge CFI-ZCP1 non-root HID access
# VID=0x054C (Sony), PID=0x0DF2 (DualSense Edge)
# Generated by scripts/hardware_setup.sh

SUBSYSTEM=="hidraw", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0df2", \
  MODE="0666", GROUP="plugdev", TAG+="uaccess"

SUBSYSTEM=="usb", ATTRS{idVendor}=="054c", ATTRS{idProduct}=="0df2", \
  MODE="0666", GROUP="plugdev", TAG+="uaccess"
UDEV_EOF

echo "  Wrote: $UDEV_RULE_FILE"
udevadm control --reload-rules
udevadm trigger
echo "  udev rules reloaded."
echo ""

# ---------------------------------------------------------------------------
# 4. USB polling rate check
# ---------------------------------------------------------------------------
echo "[3/4] Checking USB polling rate..."
# Default Linux USB polling is 125 Hz (8ms). DualSense reports at up to 1000 Hz.
# To enable 1kHz: add usbhid.mousepoll=1 to kernel boot parameters.
if grep -q "usbhid.mousepoll=1" /proc/cmdline 2>/dev/null; then
  echo "  USB polling rate: 1kHz (usbhid.mousepoll=1 detected) — optimal."
else
  echo "  USB polling rate: default (125 Hz = 8ms intervals)."
  echo "  For 1kHz polling: add 'usbhid.mousepoll=1' to GRUB_CMDLINE_LINUX_DEFAULT"
  echo "  in /etc/default/grub, then: sudo update-grub && sudo reboot"
  echo "  NOTE: 125 Hz is sufficient for PITL testing; 1kHz improves L5 timing resolution."
fi
echo ""

# ---------------------------------------------------------------------------
# 5. Connection test
# ---------------------------------------------------------------------------
echo "[4/4] Connection test..."
python3 - << 'PYEOF'
import sys
try:
    import hid
    devices = hid.enumerate(0x054C, 0x0DF2)
    if devices:
        d = devices[0]
        print(f"  FOUND: {d.get('product_string', 'DualSense Edge')} "
              f"VID=0x{d['vendor_id']:04X} PID=0x{d['product_id']:04X}")
        print(f"  Path: {d.get('path', 'N/A')}")
    else:
        print("  NOT FOUND: DualShock Edge not detected.")
        print("  Ensure controller is connected via USB (not Bluetooth) and powered on.")
        sys.exit(1)
except ImportError:
    print("  WARNING: hidapi not installed — run: pip install hidapi")
    sys.exit(0)
PYEOF

echo ""
echo "=== Setup complete ==="
echo "Run hardware tests with:"
echo "  pytest tests/hardware/ -v -m hardware"
echo ""
echo "Capture a calibration session:"
echo "  python scripts/capture_session.py --duration 60"
