"""
Tournament Operator Gate API — Phase 29

HMAC-SHA256 signed eligibility endpoint for tournament operators.

Game servers can verify humanity credentials without blockchain knowledge.
Uses a single shared secret (OPERATOR_API_KEY env var) for v1.

Endpoints:
  GET  /health                     — API status + key-configured flag
  GET  /gate/{device_id}?api_key=  — Single-device eligibility check (signed)
  POST /gate/batch?api_key=        — Batch eligibility check (up to 50 devices)

Response signature:
  sig = HMAC-SHA256(f"{device_id}:{int(eligible)}:{timestamp}", api_key).hexdigest()
  Operators verify this to confirm the response was generated by the bridge.

Security:
  - api_key compared with hmac.compare_digest() (constant-time, no timing attacks)
  - 503 if OPERATOR_API_KEY not set (graceful degradation, not an auth bypass)
  - 403 if key is wrong
"""

import collections
import hashlib
import hmac
import json as _json
import logging
import time

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

log = logging.getLogger(__name__)

_BATCH_CAP = 50


class _RateLimiter:
    """Sliding-window in-memory rate limiter (zero external dependencies).

    Tracks per-key request timestamps in a deque; evicts entries outside the
    60-second window on each check. Thread-safe in asyncio single-threaded context.
    """

    def __init__(self, requests_per_minute: int = 60):
        self._rpm = max(1, requests_per_minute)
        self._windows: collections.defaultdict = collections.defaultdict(collections.deque)

    def is_allowed(self, key: str) -> bool:
        """Return True if key is within rate limit; record this request."""
        now = time.monotonic()
        cutoff = now - 60.0
        dq = self._windows[key]
        while dq and dq[0] <= cutoff:
            dq.popleft()
        if len(dq) >= self._rpm:
            return False
        dq.append(now)
        return True


class AgentRequest(BaseModel):
    """Request body for POST /agent."""

    session_id: str
    message: str


def create_operator_app(cfg, store, _agent=None) -> FastAPI:
    """Create the Operator Gate API sub-app.

    Args:
        cfg:   Config instance (reads cfg.operator_api_key).
        store: Store instance (reads PHG checkpoints and credential mints).
    """

    app = FastAPI(title="VAPI Operator Gate API", version="1.0.0-phase36")

    # Phase 36: Per-instance rate limiter (not a global singleton)
    _rpm = int(getattr(cfg, "rate_limit_per_minute", 60))
    _limiter = _RateLimiter(requests_per_minute=_rpm)

    # Lazy-initialised BridgeAgent (None until first /agent request)
    _agent_instance = [_agent]

    def _get_agent():
        """Return the BridgeAgent instance, creating it on first call."""
        if _agent_instance[0] is None:
            try:
                from .bridge_agent import BridgeAgent
                _agent_instance[0] = BridgeAgent(cfg, store)
            except ImportError:
                raise HTTPException(
                    503, "anthropic package not installed (pip install anthropic)"
                )
        return _agent_instance[0]

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _check_key(api_key: str) -> None:
        """Raise HTTP 503/403 if key is missing or wrong."""
        if not cfg.operator_api_key:
            raise HTTPException(503, "Operator API not configured (OPERATOR_API_KEY not set)")
        if not hmac.compare_digest(api_key, cfg.operator_api_key):
            raise HTTPException(403, "Invalid API key")

    def _check_rate(api_key: str) -> None:
        """Raise HTTP 429 if the api_key has exceeded the sliding-window rate limit (Phase 36)."""
        if not _limiter.is_allowed(api_key):
            raise HTTPException(
                status_code=429,
                detail="Rate limit exceeded",
                headers={"Retry-After": "60"},
            )

    def _sign(device_id: str, eligible: bool, ts: int) -> str:
        """Produce HMAC-SHA256 signature over device_id:eligible:timestamp."""
        msg = f"{device_id}:{int(eligible)}:{ts}".encode()
        return hmac.new(
            cfg.operator_api_key.encode(), msg, hashlib.sha256
        ).hexdigest()

    def _gate_response(device_id: str) -> dict:
        """Build a signed gate response dict for one device."""
        ts = int(time.time())
        checkpoint = store.get_last_phg_checkpoint(device_id)
        credential = store.get_credential_mint(device_id)
        score = checkpoint["last_committed_score"] if checkpoint else 0
        eligible = score > 0
        cred_id = credential["credential_id"] if credential else None
        sig = _sign(device_id, eligible, ts)
        return {
            "device_id":       device_id,
            "eligible":        eligible,
            "cumulative_score": score,
            "credential_id":   cred_id,
            "timestamp":       ts,
            "sig":             sig,
        }

    # ------------------------------------------------------------------
    # Routes
    # ------------------------------------------------------------------

    @app.get("/health")
    def health():
        """API liveness check — does NOT require api_key."""
        return {
            "status": "ok",
            "operator_key_configured": bool(cfg.operator_api_key),
        }

    @app.get("/gate/{device_id}")
    def gate(device_id: str, api_key: str = Query(..., description="Shared operator API key")):
        """Single-device eligibility check with HMAC-signed response."""
        _check_key(api_key)
        _check_rate(api_key)
        return _gate_response(device_id)

    @app.post("/gate/batch")
    def gate_batch(
        device_ids: list[str],
        api_key: str = Query(..., description="Shared operator API key"),
    ):
        """Batch eligibility check for up to 50 device IDs."""
        _check_key(api_key)
        _check_rate(api_key)
        return [_gate_response(d) for d in device_ids[:_BATCH_CAP]]

    @app.post("/agent")
    def agent_chat(
        req: AgentRequest,
        api_key: str = Query(..., description="Shared operator API key"),
    ):
        """Conversational AI agent for natural-language protocol queries (Phase 30).

        Requires OPERATOR_API_KEY. Uses Claude to reason over real bridge data
        via tool_use. Session history is preserved in SQLite by session_id (Phase 31).

        Requires: pip install anthropic (503 if not installed).
        """
        _check_key(api_key)
        _check_rate(api_key)
        try:
            return _get_agent().ask(req.session_id, req.message)
        except ImportError:
            raise HTTPException(
                503, "anthropic package not installed (pip install anthropic)"
            )
        except Exception as exc:
            log.error("BridgeAgent error: %s", exc)
            raise HTTPException(500, f"Agent error: {exc}")

    @app.get("/agent/stream")
    async def agent_stream(
        session_id: str,
        message: str,
        api_key: str = Query(..., description="Shared operator API key"),
    ):
        """Streaming BridgeAgent via Server-Sent Events (Phase 31).

        Events (text/event-stream):
          {"type": "text_delta", "text": str}        — incremental response text
          {"type": "tool_start", "tool": str}        — agent invoking a bridge tool
          {"type": "tool_result", "tool": str, "preview": str}
          {"type": "done", "tools_used": list[str]}  — stream complete
          {"type": "error", "message": str}          — non-fatal error

        Requires: pip install anthropic (error event if not installed).
        """
        _check_key(api_key)
        _check_rate(api_key)
        ag = _get_agent()

        async def _generate():
            try:
                async for event in ag.stream_ask(session_id, message):
                    yield f"data: {_json.dumps(event)}\n\n"
            except ImportError:
                yield f"data: {_json.dumps({'type': 'error', 'message': 'anthropic not installed'})}\n\n"
            except Exception as exc:
                log.error("agent stream error: %s", exc)
                yield f"data: {_json.dumps({'type': 'error', 'message': str(exc)})}\n\n"

        return StreamingResponse(
            _generate(),
            media_type="text/event-stream",
            headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
        )

    @app.get("/insights")
    def get_insights(
        limit: int = 20,
        api_key: str = Query(..., description="Shared operator API key"),
    ):
        """Return most recent proactive protocol insights (Phase 32).

        Returns insights DESC by created_at. Max limit=100.
        Includes anomaly reactions (from react()), cluster alerts, trajectory flags,
        and eligibility horizon notifications — all generated by ProactiveMonitor.
        """
        _check_key(api_key)
        _check_rate(api_key)
        return store.get_recent_insights(limit=min(limit, 100))

    @app.get("/federation/clusters")
    def federation_clusters(
        limit: int = 50,
        api_key: str = Query(..., description="Shared operator API key"),
    ):
        """Return locally-detected clusters shared with the federation (Phase 34).

        Only returns is_local=True records to prevent echo amplification when
        peers query this endpoint. Max limit=200.
        """
        _check_key(api_key)
        _check_rate(api_key)
        return store.get_federation_clusters(limit=min(limit, 200), is_local=True)

    @app.get("/digest")
    def get_digest(
        window: str = "all",
        api_key: str = Query(..., description="Shared operator API key"),
    ):
        """Return synthesized longitudinal insight digests (Phase 35).

        window: '24h', '7d', '30d', or 'all' (default) for all windows.
        Also returns device risk trajectory labels (stable/warming/critical/cleared).
        """
        _check_key(api_key)
        _check_rate(api_key)
        if window == "all":
            digests = store.get_all_latest_digests()
        elif window in ("24h", "7d", "30d"):
            d = store.get_latest_digest(window)
            digests = [d] if d else []
        else:
            raise HTTPException(status_code=400, detail="window must be '24h', '7d', '30d', or 'all'")
        return {
            "digests":          digests,
            "critical_devices": store.get_devices_by_risk_label("critical"),
            "warming_devices":  store.get_devices_by_risk_label("warming"),
            "synthesis_available": len(digests) > 0,
        }

    @app.get("/enforcement")
    def get_enforcement(
        device_id: str = "",
        api_key: str = Query(..., description="Shared operator API key"),
    ):
        """Return credential enforcement state (Phase 37).

        device_id provided: returns enforcement state for that specific device.
        device_id omitted:  returns all currently suspended credentials.

        Response includes enforcement_enabled and min_consecutive_windows
        configuration values so callers can understand the policy settings.
        """
        _check_key(api_key)
        _check_rate(api_key)
        if device_id.strip():
            row = store.get_credential_enforcement(device_id.strip())
            suspended_devices = [row] if row else []
        else:
            suspended_devices = store.get_all_suspended_credentials()
        return {
            "suspended_count":         len([d for d in suspended_devices if d.get("suspended")]),
            "suspended_devices":       [d for d in suspended_devices if d.get("suspended")],
            "enforcement_enabled":     bool(getattr(cfg, "phg_credential_enforcement_enabled", True)),
            "min_consecutive_windows": int(getattr(cfg, "credential_enforcement_min_consecutive", 2)),
        }

    return app
